version: "3.7"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
  frontend:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app      
  backend:
    build:
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app